### ISSUE TITLE
Found a way to use KaTeX and work with custom deployments (like on Vercel)

### ISSUE THREAD

**Issue by spencerwooo** [foambubble/foam#246]
I found a really *not-hacky-at-all* way to use KaTeX instead of MathJax. Basically you'll need to:

- Install [linjer/jekyll-katex](https://github.com/linjer/jekyll-katex) as a plugin (and load KaTeX CSS and JS via HTML tags).
- Install all the deps that `github-pages` used to install for you.
- And finally, get rid of the `github-pages` plugin.

Because `linjer/jekyll-katex` doesn't play well with `github-pages` plugins (will run into issues like: [The tag katex is not a recognized Liquid tag](https://github.com/linjer/jekyll-katex/issues/33)), so I resolved to deploying to Vercel instead (which is equally easy and comes with built in CDN as a bonus!).

Here's my `Gemfile` and `_config.yml` for reference.

```ruby
# Gemfile

source "https://rubygems.org"

gem "jekyll"
gem "kramdown-parser-gfm"
gem "jekyll-theme-primer"
gem "jekyll-optional-front-matter"
gem "jekyll-default-layout"
gem "jekyll-relative-links"
gem "jekyll-readme-index"
gem "jekyll-titles-from-headings"
gem "jekyll-katex"
```

```yaml
# _config.yml

title: Foam

plugins:
  - jekyll-katex
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

theme: jekyll-theme-primer
repository: user/repo
permalink: pretty
```

Also, `linjer/jekyll-katex` expects `$ ... $` and `$$ ... $$` to be written inside `{% katexmm %} ... {% endkatexmm %}`, so I added both of these liquid tags in my `home.html` and `page.html`:

```html
<!-- home.html, page.html -->
---
layout: default
---

{% katexmm %} {{ content }} {% endkatexmm %}
```

And the results: https://foam-wiki.vercel.app/iqa

![image](https://user-images.githubusercontent.com/32114380/92359159-62135080-f11d-11ea-88d1-bd44a8bad76f.png)

PS: I'm willing to contribute guides to this functionality as well as instructions to deploying to Vercel if you want!
