### ISSUE TITLE
[Templates v2] Add the ability to use VS Code snippet variables in template metadata

### ISSUE THREAD

**Issue by movermeyer** [foambubble/foam#692]
#655 added metadata to templates, including the `filepath` attribute.

As part of #534, I had dreamed of being able to use any [VS Code snippet variable](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables) in the `filepath`.

```yaml
---
foam_template:
  filepath: `journal/${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE}.md`
---
```

This would allow `Foam: Open Daily Note` to make use of templates easily.
However, this is not currently possible. VS Code does not currently offer an interface for resolving the snippet variables without opening the snippet in an editor for the user.

---

Figure out a workaround, or get VS Code to expose an interface that would suit our needs.
