### ISSUE TITLE
filepath - setting from foam_template is ignored when creating note from template

### ISSUE THREAD

**Issue by matthiasdaues** [foambubble/foam#842]
- Foam version: v0.15.8
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes 

**Summary**
The filepath string from the "foam_template"-YAML-block is ignored when creating a note from template. 

**Steps to reproduce**
1. Select F1 -> Foam: Create New Note From Template
2. Enter a title in the prompt
3. Enter a filename in the prompt

**Additional information**

The YAML frontmatter looks like this:

```yaml
---
tags: note, ${1:Tag1}
author: ${2:user}
bibliography: [/home/user/Zotero/export/zotero.bib]
title: $FOAM_TITLE
foam_template: # foam template metadata
    filepath: "/home/user/zettelkasten/$FOAM_DATE_YEAR$FOAM_DATE_MONTH$FOAM_DATE_DATE$FOAM_DATE_HOUR$FOAM_DATE_MINUTE $FOAM_TITLE.md"
    name: 01 - Notiz
    description: Ein generischer Zettel für alle Fälle
---
```
Step 3 should not happen, since the filepath is stated as an absolute path.
