### ISSUE TITLE
Alt+D does not open daily note when already existent

### ISSUE THREAD

**Issue by femto-code** [foambubble/foam#967]
### Describe the bug

> If a Daily Note for today’s date already exists, the command opens the existing note.

This does not seem to happen in my case...it opens a file path dialog
<img width="458" alt="Screenshot 2022-04-02 152520" src="https://user-images.githubusercontent.com/59444046/161385581-90a17088-29b2-426c-9ad9-ddfe804a98a6.png">
The path is filled in correctly (exactly matching my `filepath` specification in daily note template).
But if I hit enter:
<img width="464" alt="Screenshot 2022-04-02 152548" src="https://user-images.githubusercontent.com/59444046/161385604-93f9e65d-f7a2-4ce5-b7bd-ceb64cea1b32.png">
It does not let me open the current daily note - it already does exist.
Btw, when the note is not created yet, `alt + d` creates it without any problem - following the daily note template.

### Steps to Reproduce the Bug or Issue

Content in `.foam/templates/daily-note.md`:

```
---
foam_template:
  filepath: "journal/$FOAM_DATE_YEAR/$FOAM_DATE_MONTH/$FOAM_DATE_YEAR-$FOAM_DATE_MONTH-$FOAM_DATE_DATE.md"
  name: "Lecture note"
  description: "Daily course notes"
type: transcript
title: "$FOAM_DATE_YEAR_SHORT-$FOAM_DATE_MONTH-$FOAM_DATE_DATE"
---
```

Press `alt +d`

### Expected behavior

I thought alt+d can also be used to open an existent daily note?

### Screenshots or Videos

see above

### Operating System Version

Tested on Windows 10 and Ubuntu 21.04

### Visual Studio Code Version

1.66.0 (VSCodium)

### Additional context

I feel like that it only happens because of the differing format in `filepath` attribute in the template...
